### ISSUE TITLE
Price missing

### ISSUE THREAD

**Issue by khs6226** [khs6226/comp2340-senior-junior-activity#1]
Add price to each items in groceries.

cabbage : $0.6 / kg
broccoli : $0.46 / kg
kale : $0.5 / kg
brussels sprouts : $2 / pack
turnip : $1.32 / pack
cauliflower : $0.77 / kg
kohlrabi : $1.2 / kg
mustard : $0.83 / kg

**Comment by kailinwei** [comment]
I will work on this issue

**Comment by khs6226** [comment]
solved
